config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'account_activations/edit'
  get 'sessions/new'
  root                'static_pages#home'
  get     'help'   => 'static_pages#help'
  get     'about'  => 'static_pages#about'
  get     'signup' => 'users#new'
  get     'login'  => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This was a tutorial followed by <a href="bydavid.me">David</a>,
  in order to learn web development with rails.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help from Jesus
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is a home page for the rails 6 tutorial done by <a href="http://www.bydavid.me/">David Adeyemi</a>
  </h2>

  <%= link_to "Sign up now!", signup_path, class: 'btn btn-lg btn-primary' %>
</div>
<%= link_to image_tag("rails.svg", alt: "Rails logo"), 'https://rubyonrails.org' %>